module.exports = {
  nightmare: {
    show: false,
    webPreferences: {
      images: false,
    },
  },
  excludeShows: {
    cbc: [
      '/still-standing/',
      '/21-thunder/',
      '/everything-indigenous/',
      '/absolutely-canadian/',
      // "/air-farce/",
      '/alias-grace/',
      '/all-our-relations/',
      // "/anne/",
      '/at-the-table/',
      '/backstage-pass/',
      // "/baroness-von-sketch-show/",
      '/becoming-canadian/',
      // "/being-erica/",
      '/bellevue/',
      '/blackstone/',
      '/bondi-vet/',
      '/bondi-vet-top-ten/',
      '/brand-canada/',
      '/camelot/',
      '/canada--a-peoples-history/',
      '/canada--the-story-of-us/',
      '/canada-reads/',
      '/canadas-smartest-person/',
      '/canadian-reflections/',
      '/catch-the-dream-bios-with-adam-beach/',
      '/cbc-music-specials/',
      '/cbc-news-specials/',
      '/coming-in/',
      // "/coronation-street/",
      '/cracked/',
      '/crash-gallery/',
      '/disrupting-design/',
      '/docs-special-presentation/',
      '/doc-zone/',
      '/documentary-channel-selections/',
      '/doing-it-with-brian--darla/',
      // "/dragons-den/",
      '/escape-to-the-chateau/',
      '/escape-to-the-country/',
      '/exhibitionists/',
      '/extraordinary-canadians/',
      '/firsthand/',
      '/follow-the-money/',
      '/fool-canada/',
      '/four-in-the-morning/',
      '/grand-designs-australia/',
      '/halifax-comedy-festival/',
      '/heartland/',
      '/hello-goodbye/',
      '/humantown/',
      '/interrupt-this-program/',
      // "/jekyll-and-hyde/",
      '/just-for-laughs-gags/',
      '/just-for-laughs-galas/',
      // "/kids-in-the-hall/",
      '/kids-that-are-kind-of-amazing-at-stuff-with-gerry-dee/',
      // "/kims-convenience/",
      '/land-and-sea-network/',
      '/land-and-sea-nfld/',
      '/live-from-the-hundred-years-cafe/',
      '/maamuitaau/',
      '/mansbridge-one-on-one/',
      '/marketplace/',
      '/michael--every-day/',
      '/michael--tuesdays--thursdays/',
      '/movies/',
      '/mr-d/',
      '/murdoch-mysteries/',
      '/my-90-year-old-roommate/',
      '/my-kitchen-can-be-anything/',
      '/newborn-moms/',
      '/pure/',
      '/q/',
      '/queer-self-portraits/',
      '/reel-east-coast/',
      '/republic-of-doyle/',
      // "/rick-mercer-report/",
      '/riftworld-chronicles/',
      '/save-me/',
      // "/schitts-creek/",
      '/scotiabank-giller-prize/',
      '/shoot-the-messenger/',
      '/short-docs/',
      '/short-film-face-off/',
      '/still-standing/',
      '/strange-empire/',
      '/stratford-presents/',
      '/taken/',
      '/terrific-women/',
      '/the-amazing-gayl-pile/',
      '/the-a-word/',
      '/the-book-of-negroes/',
      '/the-fifth-estate/',
      '/the-filmmakers/',
      '/the-goods/',
      '/the-great-british-baking-show/',
      '/the-honourable-woman/',
      '/the-investigators/',
      '/the-national/',
      '/the-nature-of-things/',
      '/the-neddeaus-of-duqesne-island/',
      '/the-passionate-eye/',
      '/the-plateaus/',
      '/the-romeo-section/',
      '/the-secret-path/',
      '/the-special-needs-hotel/',
      '/the-whole-truths/',
      '/this-art-works/',
      // "/this-hour-has-22-minutes/",
      '/this-life/',
      '/true-north-calling/',
      '/we-are-canada/',
      '/when-calls-the-heart/',
      '/winnipeg-comedy-festival/',
      '/workin-moms/',
      '/x-company/',
      '/young-drunk-punk/',
    ],
    space: [
      // '/killjoys/',
      // '/blood-drive/',
      // '/wynonna-earp/',
      // '/doctor-who/',
      // '/orphan-black/',
      '/face-off/',
      '/innerspace/',
      // '/dark-matter/',
      '/cosplay-melee/',
      '/star-trek-discovery/',
      // '/supernatural/',
      // '/the-expanse/',
      // '/class/',
      // '/aftermath/',
      // '/the-librarians/',
      // '/stargate-sg-1/',
      // '/z-nation/',
      '/stan-lees-lucky-man/',
      // '/the-last-ship/',
    ],
    comedy: [
      '/midnight',
      '/TheBeaverton',
      // "/TheBigBangTheory",
      // "/Broad-City",
      '/CashCab',
      '/ComedyNow',
      // "/CornerGas",
      // "/TheDailyShow",
      // "/DrunkHistory",
      // "/Frasier",
      // "/FullFrontal",
      // "/InsideAmySchumer",
      '/TheJimJefferiesShow',
      '/JimmyKimmelLIve',
      '/JFL',
      '/JustForLaughsAllAccess',
      '/JustForLaughsGags',
      // "/KingOfQueens",
      '/LOL',
      '/Movies',
      '/ThePresidentShow',
      '/TheRedGreenShow',
      // "/SouthPark",
      '/Tosh',
      '/Workaholics',
      '/Wrecked',
    ],
    much: [
      '/we-day-canada/',
      '/dan-for-a-week/',
      '/conan/',
      '/idiotsitter/',
      '/tosh0/',
      '/drunk-history-uk/',
      '/countdown/',
      '/team-ninja-warrior/',
      // '/south-park/',
      '/legends-of-chamberlain-heights/',
    ],
    citytv: [
      '/americas-got-talent/',
      '/bachelor-in-paradise/',
      '/beat-shazam/',
      // '/bobs-burgers/',
      '/celebrity-family-feud/',
      '/city-fall-preview/',
      '/redcarpetlive/',
      '/little-big-shots/',
      '/little-big-shots-forever-young/',
      '/love-connection/',
      // '/nirvanna-the-band-the-show/',
      '/prison-break/',
      '/secondjen/',
      '/grammys/',
      '/the-bachelorette/',
      '/the-gong-show/',
      '/to-tell-the-truth/',
      // '/bad-blood/',
      '/ghosted/',
      '/la-vegas/',
      '/speechless/',
      // '/the-blacklist/',
      // "/the-orville/",
      '/the-resident/',
      '/versailles/',
      // '/brooklyn-nine-nine/',
      // '/family-guy/',
      '/hells-kitchen/',
      '/lethal-weapon/',
      '/life-in-pieces/',
      // '/modern-family/',
      '/mom/',
      // '/new-girl/',
      '/scorpion/',
      '/the-bachelor/',
      // '/the-last-man-on-earth/',
      '/the-mick/',
      '/the-middle/',
      '/hockey-night-in-canada/',
      '/nfl/',
      '/breakfast-television-toronto/',
      '/cityline/',
      '/entertainment-city/',
      '/general-hospital/',
      '/lets-make-a-deal/',
      '/the-chew/',
      '/the-price-is-right/',
      '/citykids/',
      '/doowett/',
      '/space-stretch/',
    ],
    global: [
      '/bigbrother/',
      '/theblacklistredemption/',
      '/bombgirls/',
      '/bull/',
      '/thecaseofjonbenetramsey/',
      '/thecelebrityapprentice/',
      '/chicagofire/',
      '/chicagojustice/',
      '/chicagomed/',
      '/chicagopd/',
      '/daysofourlives/',
      '/elementary/',
      '/emeraldcity/',
      '/thegoodplace/',
      '/thegreatindoors/',
      '/hawaiifive0/',
      '/houdinianddoyle/',
      '/kevincanwait/',
      // '/thelateshowwithstephencolbert/',
      '/macgyver/',
      '/madamsecretary/',
      '/manwithaplan/',
      '/marykillspeople/',
      '/midnighttexas/',
      '/ncis/',
      '/ncislosangeles/',
      '/ncisneworleans/',
      '/thenightshift/',
      '/pgatour/',
      '/privateeyes/',
      '/therachaelrayshow/',
      '/ransom/',
      '/rookieblue/',
      '/salvation/',
      // '/saturdaynightlive/',
      '/shadesofblue/',
      '/somewherebetween/',
      '/spartanultimateteamchallenge/',
      '/superstore/',
      '/survivor/',
      '/taken/',
      '/thetalk/',
      '/timeless/',
      '/thewall/',
      '/theyoungandtherestless/',
    ],
    adultswim: [],
    bravo: [
      '/Shooter',
      '/Claws',
      '/DaytimeDivas',
      // '/TheHandmaidsTale',
      '/QueenOfTheSouth',
      // '/QueenSugar',
      // '/Suits',
      '/FamousInLove',
      '/Pretty-Little-Liars',
      '/projectrunway',
      '/19-2',
      '/Good-Behavior',
      '/TheArrangement',
      '/Animal-Kingdom',
      '/BlueBloods',
      '/bones',
      // '/Castle',
      '/Chance',
      '/Colony',
      '/Conviction',
      '/CriminalMinds',
      '/DesignatedSurvivor',
      '/TheFall',
      '/Falling-Water',
      '/Guilt',
      '/lawandordersvu',
      '/LifeSentence',
      '/Listener',
      '/Motive',
      '/murderinthefirst',
      '/PhilipKDicksElectricDreams',
      '/projectrunwayjunior',
      '/ProjectRunwayFashionStartUp',
      '/Underground',
    ],
    trutv: [
      // "adam-ruins-everything",
      'at-home-with-amy-sedaris',
      // "billy-on-the-street",
      'bobcat-goldthwaits-misfits-and-monsters',
      'the-carbonaro-effect',
      // "the-chris-gethard-show",
      'chris-webbers-full-court-pranks',
      'comedy-knockout',
      'fameless',
      'greatest-ever',
      'hack-my-life',
      'hack-my-life-inside-hacks',
      'im-sorry',
      'impractical-jokers',
      'impractical-jokers-after-party',
      'impractical-jokers-inside-jokes',
      'jon-glaser-loves-gear',
      'ncaa',
      // "the-problem-with-apu",
      'late-night-snack',
      'talk-show-the-game-show',
      'those-who-cant',
      'trutv-top-funniest',
      'upscale-with-prentice-penny',
    ],
  },
  includeShows: {
    // 'south-park': 'south-park',
    TheDailyShow: 'the-daily-show',
    FullFrontal: 'full-frontal',
    anne: 'anne',
    'baroness-von-sketch-show': 'baroness-von-sketch-show',
    // 'coronation-street': // 'coronation-street', // fix
    // 'dragons-den': 'dragons-den',
    'kims-convenience': 'kim-s-convenience',
    // 'kids-in-the-hall': 'the-kids-in-the-hall',
    // 'my-90-year-old-roommate': // 'my-90-year-old-roommate', // fix
    // 'rick-mercer-report': 'rick-mercer-report',
    // 'schitts-creek': 'schitts-creek',
    // 'this-hour-has-22-minutes': 'this-hour-has-22-minutes',
    // 'young-drunk-punk': 'young-drunk-punk',
    // 'saturdaynightlive': 'saturday-night-live'
  },
};
